CREATE TABLE ARTICOLI (
	CODICE VARCHAR(15) NOT NULL,
	DESCRIZIONE VARCHAR(50) NOT NULL, 
	DES_BREVE VARCHAR(24), 
	CATEGORIA INTEGER NOT NULL, 
	PREZZO INTEGER NOT NULL, 
	TIPO VARCHAR(3)NOT NULL, 
	COLORE INTEGER NOT NULL, 
	ALQIVA VARCHAR(2)NOT NULL, 
	REPARTO INTEGER NOT NULL, 
	PRIMARY KEY ( CODICE ));

CREATE TABLE CATEGORIE (
	ID_CAT INTEGER NOT NULL, 
	DES_CAT VARCHAR(15) NOT NULL, 
	PRIMARY KEY(ID_CAT));

CREATE TABLE TIPI_ARTICOLO (
	ID_TIPART VARCHAR(3) NOT NULL, 
	DES_TIPART VARCHAR(15) NOT NULL, 
	PRIMARY KEY(ID_TIPART));

INSERT INTO TIPI_ARTICOLO
	(ID_TIPART,DES_TIPART)
	VALUES
	('STD','STANDART');

CREATE TABLE ALIQUOTE_IVA ( 
	ID_ALQIVA VARCHAR(2) NOT NULL, 
	DES_ALQIVA VARCHAR(15) NOT NULL, 
	PRIMARY KEY(ID_ALQIVA));

INSERT INTO ALIQUOTE_IVA
	(ID_ALQIVA,DES_ALQIVA)
	VALUES
	('ES','IVA ESENTE');

INSERT INTO ALIQUOTE_IVA
	(ID_ALQIVA,DES_ALQIVA)
	VALUES
	('04','IVA 04%');

INSERT INTO ALIQUOTE_IVA
	(ID_ALQIVA,DES_ALQIVA)
	VALUES
	('10','IVA 10%');

INSERT INTO ALIQUOTE_IVA
	(ID_ALQIVA,DES_ALQIVA)
	VALUES
	('22','IVA 22%');

CREATE TABLE MOVIMENTI (
	ID_MOV INTEGER NOT NULL, 
	TIPO_MOV VARCHAR(4) NOT NULL, 
	NUMERO_MOV INTEGER, 
	DATA_MOV INTEGER NOT NULL, 
	ID_CLIENTE INTEGER NOT NULL, 
	PRIMARY KEY ( ID_MOV ));

CREATE TABLE MOVIMENTI_RIGHE (
	ID_RIG INTEGER NOT NULL, 
	ID_MOV INTEGER NOT NULL, 
	QTA INTEGER, 
	ID_ART_MOV INTEGER NOT NULL, 
	NOTE VARCHAR(50), 
	PRIMARY KEY ( ID_MOV ));

CREATE TABLE CLIENTI (
	ID_CLI INTEGER NOT NULL, 
	RAGSOC_CLI VARCHAR(30) NOT NULL, 
	PIVA VARCHAR(11), 
	PRIMARY KEY ( ID_CLI ));

